# Generated by Django 2.2.1 on 2019-07-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190703_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='correcta',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
