# Generated by Django 2.2.1 on 2019-07-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190707_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='correcto',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
