# Generated by Django 2.2.1 on 2019-07-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190707_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='op_correcta',
            field=models.BooleanField(default=False),
        ),
    ]
