# Generated by Django 2.2.1 on 2019-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190711_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='op_correcta',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
