# Generated by Django 2.2.1 on 2019-07-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190711_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='op_correcta',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=100, verbose_name='Question'),
        ),
    ]
