# Generated by Django 2.2.1 on 2019-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190711_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.BooleanField(default=False, verbose_name='Correct answer'),
        ),
    ]
