# Generated by Django 2.2.1 on 2019-07-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190711_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='respuesta',
        ),
    ]
