# Generated by Django 2.2.1 on 2019-07-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20190712_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='respuesta',
            field=models.BooleanField(default=False, verbose_name='Correct answer, classChoice,respuesta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=100, verbose_name='Question,question_text'),
        ),
    ]
